---

- name: set attached managed policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_attached_managed_policies: >
      {{ _aws_iam_aad
         | json_query(_aws_iam_Entity_Type
                      + "DetailList[?"
                      + _aws_iam_Entity_Type
                      + "Name == `"
                      + _aws_iam_entity_name
                      + "`].AttachedManagedPolicies[].PolicyArn") }}

- name: remove all managed policies for {{ _aws_iam_e }}
  command: >
    aws iam detach-{{ _aws_iam_entity_type }}-policy
            --{{ _aws_iam_entity_type }}-name '{{ _aws_iam_entity_name }}'
            --policy-arn '{{ item }}'
            --profile '{{ aws_profile }}'
  with_items: '{{ _aws_iam_attached_managed_policies }}'
