---

- name: set instance profiles fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_instance_profiles: >
      {{ _aws_iam_aad
         | json_query("RoleDetailList[?RoleName == `"
                      + _aws_iam_entity_name
                      + "`].InstanceProfileList[*].InstanceProfileName[]") }}

- name: remove {{ _aws_iam_e }} from instance profiles
  command: >
    aws iam remove-{{ _aws_iam_entity_type }}-from-instance-profile
            --instance-profile-name '{{ item }}'
            --{{ _aws_iam_entity_type }}-name '{{ _aws_iam_entity_name }}'
            --query 'InstanceProfiles[*].InstanceProfileName'
            --profile '{{ aws_profile }}'
  with_items: '{{ _aws_iam_instance_profiles }}'
