---

- name: set IAM entity name fact
  set_fact:
    entity_name: '{{ item }}'

- name: set configuration fact for IAM {{ entity_type }}s
  set_fact:
    configured_entities: '{{ vars["iam_" + entity_type + "s"] }}'

- name: create IAM {{ entity_type }} {{ entity_name }}
  iam:
    groups: '{{ configured_entities[entity_name]["groups"] | default(omit) }}'
    iam_type: '{{ entity_type }}'
    name: '{{ entity_name }}'
    profile: '{{ profile }}'
    state: present

- name: list managed policies attached to
        IAM {{ entity_type }} {{ entity_name }}
  command: |
    aws iam list-attached-{{ entity_type }}-policies
            --{{ entity_type }}-name '{{ entity_name }}'
            --query 'AttachedPolicies[*].PolicyArn'
            --profile '{{ profile }}'
  register: attached_managed_policies
  changed_when: False

- name: set attached managed policies fact for
        IAM {{ entity_type }} {{ entity_name }}
  set_fact:
    attached_managed_policies:
      '{{ attached_managed_policies.stdout | from_json }}'

- debug: var=attached_managed_policies

- name: set configured managed policies fact for
        IAM {{ entity_type }} {{ entity_name }}
  set_fact:
    configured_managed_policies:
      '{{ configured_entities[entity_name]["policies"] | default([]) }}'

- name: attach managed policies to IAM {{ entity_type }} {{ entity_name }}
  command: |
    aws iam attach-{{ entity_type }}-policy
            --{{ entity_type }}-name '{{ entity_name }}'
            --policy-arn '{{ item }}'
            --profile '{{ profile }}'
  with_items: configured_managed_policies
  when: item not in attached_managed_policies

- name: detach managed policies from IAM {{ entity_type }} {{ entity_name }}
  command: |
    aws iam detach-{{ entity_type }}-policy
            --{{ entity_type }}-name '{{ entity_name }}'
            --policy-arn '{{ item }}'
            --profile '{{ profile }}'
  with_items: attached_managed_policies
  when: item not in configured_managed_policies
