---

- name: list member groups for {{ e }}
  command: >
    aws iam list-groups-for-{{ entity_type }}
            --{{ entity_type }}-name '{{ entity_name }}'
            --query 'Groups[*].GroupName'
            --profile '{{ aws_profile }}'
  register: member_groups
  changed_when: False

- name: set member groups fact for {{ e }}
  set_fact:
    member_groups: '{{ member_groups.stdout | from_json | sort }}'

- name: set configured groups fact for {{ e }}
  set_fact:
    configured_groups:
      '{{ configured_entities[entity_name]["groups"] | default([]) | sort }}'

- name: set added groups fact for {{ e }}
  set_fact:
    added_groups: >
      {{ configured_groups | difference(member_groups) }}

- name: set removed groups fact for {{ e }}
  set_fact:
    removed_groups: >
      {{ member_groups | difference(configured_groups) }}

- name: add {{ e }} to groups
  command: >
    aws iam add-{{ entity_type }}-to-group
            --group-name '{{ item }}'
            --{{ entity_type }}-name '{{ entity_name }}'
            --profile '{{ aws_profile }}'
  with_items: added_groups

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      added <a href="{{ eurl }}">{{ e }}</a> to
      {% if added_groups.__len__() == 1 -%}
      group{% else -%}groups{% endif %}
      {% for group in added_groups -%}
      <a href="https://console.aws.amazon.com/iam/home#groups/{{
        group }}">{{ group }}</a>{%
      if not loop.last -%}, {% endif -%}
      {% endfor %}
      in <a href="{{ iam_url }}">account {{ aws_profile }}</a>
  when: >
    notifier_role is defined and
    added_groups

- name: remove {{ e }} from groups
  command: >
    aws iam remove-{{ entity_type }}-from-group
            --group-name '{{ item }}'
            --{{ entity_type }}-name '{{ entity_name }}'
            --profile '{{ aws_profile }}'
  with_items: removed_groups

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      removed <a href="{{ eurl }}">{{ e }}</a> from
      {% if removed_groups.__len__() == 1 -%}
      group{% else -%}groups{% endif %}
      {% for group in removed_groups -%}
      <a href="https://console.aws.amazon.com/iam/home#groups/{{
        group }}">{{ group }}</a>{%
      if not loop.last -%}, {% endif -%}
      {% endfor %}
      in <a href="{{ iam_url }}">account {{ aws_profile }}</a>
  when: >
    notifier_role is defined and
    removed_groups
