---

- name: list managed policies attached to {{ _aws_iam_e }}
  command: >
    aws iam list-attached-{{ _aws_iam_entity_type }}-policies
            --{{ _aws_iam_entity_type }}-name '{{ _aws_iam_entity_name }}'
            --query 'AttachedPolicies[*].PolicyArn'
            --profile '{{ aws_profile }}'
  register: _aws_iam_attached_managed_policies
  changed_when: False

- name: set attached managed policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_attached_managed_policies: >
      {{ _aws_iam_attached_managed_policies.stdout | from_json | sort }}

- name: set configured managed policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_configured_managed_policies: >
      {{ _aws_iam_configured_entities[_aws_iam_entity_name]["managed_policies"]
         | default([]) | sort }}

- name: set added managed policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_added_managed_policies: >
      {{ _aws_iam_configured_managed_policies
         | difference(_aws_iam_attached_managed_policies) }}

- name: set removed managed policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_removed_managed_policies: >
      {{ _aws_iam_attached_managed_policies
         | difference(_aws_iam_configured_managed_policies) }}
