---

- name: list managed policies attached to {{ e }}
  command: >
    aws iam list-attached-{{ entity_type }}-policies
            --{{ entity_type }}-name '{{ entity_name }}'
            --query 'AttachedPolicies[*].PolicyArn'
            --profile '{{ profile }}'
  register: attached_managed_policies
  changed_when: False

- name: set attached managed policies fact for {{ e }}
  set_fact:
    attached_managed_policies: >
      {{ attached_managed_policies.stdout | from_json | sort }}

- name: set configured managed policies fact for {{ e }}
  set_fact:
    configured_managed_policies: >
      {{ configured_entities[entity_name]["managed_policies"]
         | default([]) | sort }}

- name: set added managed policies fact for {{ e }}
  set_fact:
    added_managed_policies: >
      {{ configured_managed_policies | difference(attached_managed_policies) }}

- name: set removed managed policies fact for {{ e }}
  set_fact:
    removed_managed_policies: >
      {{ attached_managed_policies | difference(configured_managed_policies) }}

- name: attach managed policies to {{ e }}
  command: >
    aws iam attach-{{ entity_type }}-policy
            --{{ entity_type }}-name '{{ entity_name }}'
            --policy-arn '{{ item }}'
            --profile '{{ profile }}'
  with_items: added_managed_policies

- name: detach managed policies from {{ e }}
  command: >
    aws iam detach-{{ entity_type }}-policy
            --{{ entity_type }}-name '{{ entity_name }}'
            --policy-arn '{{ item }}'
            --profile '{{ profile }}'
  with_items: removed_managed_policies

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      updated attached managed policies
      for <a href="{{ eurl }}">{{ e }}</a>
      in <a href="{{ iam_url }}">account {{ profile }}</a>
    attachments:
    - text:
      mrkdwn_in: ['fields']
      fields:

      - title: old attached managed policies
        value: >
          {% if not attached_managed_policies %}(none){% endif -%}
          {% for policy in attached_managed_policies
          %}<pre>{{ policy }}</pre>{% if not loop.last %}<br/>{% endif
          %}{% endfor %}
        short: true

      - title: new attached managed policies
        value: >
          {% if not configured_managed_policies %}(none){% endif -%}
          {% for policy in configured_managed_policies
          %}<pre>{{ policy }}</pre>{% if not loop.last %}<br/>{% endif
          %}{% endfor %}
        short: true

  when: >
    notifier_role is defined and
    attached_managed_policies != configured_managed_policies
