---

- name: set embedded inline policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_embedded_inline_policies: >
      {{ _aws_iam_aad
         | json_query(_aws_iam_Entity_Type
                      + "DetailList[?"
                      + _aws_iam_Entity_Type
                      + "Name == `"
                      + _aws_iam_entity_name
                      + "`]."
                      + _aws_iam_Entity_Type
                      + "PolicyList[].PolicyName") }}

- name: delete all inline policies for {{ _aws_iam_e }}
  command: >
    aws iam delete-{{ _aws_iam_entity_type }}-policy
            --{{ _aws_iam_entity_type }}-name '{{ _aws_iam_entity_name }}'
            --policy-name '{{ item }}'
            --profile '{{ aws_profile }}'
  with_items: '{{ _aws_iam_embedded_inline_policies }}'
