---

- name: set IAM entity name fact
  set_fact:
    entity_name: '{{ item }}'

- name: set configuration fact for IAM {{ entity_type }}s
  set_fact:
    configured_entities: '{{ vars["iam_" + entity_type + "s"] }}'

- name: create IAM {{ entity_type }} {{ entity_name }}
  iam:
    groups: '{{ configured_entities[entity_name]["groups"] | default(omit) }}'
    iam_type: '{{ entity_type }}'
    name: '{{ entity_name }}'
    profile: '{{ profile }}'
    state: present
  register: iam

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      created <b>IAM {{ entity_type }} {{ entity_name }}</b>
      in <b>account {{ profile }}</b>
  when: >
    notifier_role is defined and
    iam.changed

- include: entity_sync_managed_policies.yml
- include: entity_sync_inline_policies.yml

- include: entity_sync_assume_role_policy.yml
  when: entity_type == 'role'
