---

- name: set IAM entity facts
  set_fact:
    entity_name: '{{ item }}'
    e: 'IAM {{ entity_type }} {{ item }}'
    eurl: https://console.aws.amazon.com/iam/home#{{ entity_type }}s/{{ item }}

- name: set configuration fact for IAM {{ entity_type }}s
  set_fact:
    configured_entities: '{{ vars["iam_" + entity_type + "s"] }}'

- include: entity_sync_managed_policies_facts.yml
- include: entity_sync_managed_policies_attach.yml
- include: entity_sync_managed_policies_detach.yml

- include: entity_sync_inline_policies_facts.yml
- include: entity_sync_inline_policies_add.yml
- include: entity_sync_inline_policies_delete.yml
- include: entity_sync_inline_policies_update.yml

- include: entity_sync_user_groups.yml
  when: entity_type == 'user'

- include: entity_sync_assume_role_policy.yml
  when: entity_type == 'role'
