---

- name: list inline policies embedded in {{ _aws_iam_e }}
  command: >
    aws iam list-{{ _aws_iam_entity_type }}-policies
            --{{ _aws_iam_entity_type }}-name '{{ _aws_iam_entity_name }}'
            --query 'PolicyNames'
            --profile '{{ aws_profile }}'
  register: _aws_iam_embedded_inline_policies
  changed_when: False

- name: set embedded inline policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_embedded_inline_policies:
      '{{ _aws_iam_embedded_inline_policies.stdout | from_json }}'

- name: delete all inline policies for {{ _aws_iam_e }}
  command: >
    aws iam delete-{{ _aws_iam_entity_type }}-policy
            --{{ _aws_iam_entity_type }}-name '{{ _aws_iam_entity_name }}'
            --policy-name '{{ item }}'
            --profile '{{ aws_profile }}'
  with_items: _aws_iam_embedded_inline_policies
