---

- name: set default configured inline policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_configured_inline_policies: []

- name: set configured inline policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_configured_inline_policies: >
      {{ _aws_iam_configured_entities[_aws_iam_entity_name]["inline_policies"].keys()
         | default([]) | sort }}
  when: >
    _aws_iam_configured_entities[_aws_iam_entity_name]["inline_policies"] is defined

- name: set configured inline policy documents fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_configured_inline_policy_documents: >
      {{ _aws_iam_configured_entities[_aws_iam_entity_name]["inline_policies"]
         | default({}) }}


- name: set embedded inline policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_embedded_inline_policies: >
      {{ _aws_iam_aad
         | json_query(_aws_iam_Entity_Type
                      + "DetailList[?"
                      + _aws_iam_Entity_Type
                      + "Name == `"
                      + _aws_iam_entity_name
                      + "`]."
                      + _aws_iam_Entity_Type
                      + "PolicyList[].PolicyName") }}

- name: set embedded inline policy documents fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_embedded_inline_policy_documents: >
      {{ _aws_iam_embedded_inline_policy_documents
         | default({})
         | combine({item: (_aws_iam_aad
                           | json_query(_aws_iam_Entity_Type
                                        + "DetailList[?"
                                        + _aws_iam_Entity_Type
                                        + "Name == `"
                                        + _aws_iam_entity_name
                                        + "`]."
                                        + _aws_iam_Entity_Type
                                        + "PolicyList[] | [?PolicyName == `"
                                        + item
                                        + "`] | [0].PolicyDocument"))}) }}
  with_items: '{{ _aws_iam_embedded_inline_policies }}'


- name: set added inline policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_added_inline_policies: >
      {{ _aws_iam_configured_inline_policies
         | difference(_aws_iam_embedded_inline_policies) }}


- name: set deleted inline policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_deleted_inline_policies: >
      {{ _aws_iam_embedded_inline_policies
         | difference(_aws_iam_configured_inline_policies) }}


- name: set default updated inline policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_updated_inline_policies: []

- name: set updated inline policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_updated_inline_policies: >
      {{ _aws_iam_updated_inline_policies | default([]) | union([item]) }}
  with_items: >
    {{ _aws_iam_configured_inline_policies
       | intersect(_aws_iam_embedded_inline_policies) }}
  when: >
    _aws_iam_embedded_inline_policy_documents[item]
    != _aws_iam_configured_inline_policy_documents[item]
