---

- name: set members fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_members: >
      {{ _aws_iam_aad
         | json_query("UserDetailList[?contains(GroupList, `"
                      + _aws_iam_entity_name
                      + "`)].UserName") }}

- name: remove all members for {{ _aws_iam_e }}
  command: >
    aws iam remove-user-from-{{ _aws_iam_entity_type }}
            --group-name '{{ _aws_iam_entity_name }}'
            --user-name '{{ item }}'
            --profile '{{ aws_profile }}'
  with_items: '{{ _aws_iam_members }}'
