---

- name: set attached managed policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_attached_managed_policies: >
      {{ _aws_iam_aad
         | json_query(_aws_iam_Entity_Type
                      + "DetailList[?"
                      + _aws_iam_Entity_Type
                      + "Name == `"
                      + _aws_iam_entity_name
                      + "`].AttachedManagedPolicies[].PolicyArn") }}

- name: set configured managed policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_configured_managed_policies: >
      {{ _aws_iam_configured_entities[_aws_iam_entity_name]["managed_policies"]
         | default([]) | sort }}

- name: set added managed policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_added_managed_policies: >
      {{ _aws_iam_configured_managed_policies
         | difference(_aws_iam_attached_managed_policies) }}

- name: set removed managed policies fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_removed_managed_policies: >
      {{ _aws_iam_attached_managed_policies
         | difference(_aws_iam_configured_managed_policies) }}
