---

- name: set IAM entity facts
  set_fact:
    _aws_iam_e: 'IAM {{ _aws_iam_entity_type }} {{ _aws_iam_entity_name }}'
    _aws_iam_eurl: >-
      https://console.aws.amazon.com/iam/home#{{
        _aws_iam_entity_type }}s/{{ _aws_iam_entity_name }}

- name: set configuration fact for IAM {{ _aws_iam_entity_type }}s
  set_fact:
    _aws_iam_configured_entities: >
      {{ vars["aws_iam_" + _aws_iam_entity_type + "s"] }}

- name: create {{ _aws_iam_e }}
  action: >
    iam_{{ _aws_iam_entity_type }}
    profile={{ aws_profile }}
    name={{ _aws_iam_entity_name }}
    state=present
  register: _aws_iam_create

- name: call optional notifier
  include_tasks: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      created <a href="{{ _aws_iam_eurl }}">{{ _aws_iam_e }}</a>
      in <a href="{{ _aws_iam_url }}">account {{ aws_profile }}</a>
  when: >
    notifier_role is defined and
    _aws_iam_create.changed
