---

- name: set IAM entity name fact
  set_fact:
    entity_name: '{{ item }}'

- include: entity_detach_managed_policies.yml
- include: entity_delete_inline_policies.yml

- include: entity_remove_group_users.yml
  when: entity_type == 'group'

- include: '{{ entity_type }}_delete.yml'

- name: remove IAM {{ entity_type }} {{ entity_name }}
  command: |
    aws iam delete-{{ entity_type }}
            --{{ entity_type }}-name '{{ entity_name }}'
            --profile '{{ profile }}'
