---

- name: set IAM entity name fact
  set_fact:
    entity_name: '{{ item }}'

- name: set configuration fact for IAM {{ entity_type }}s
  set_fact:
    configured_entities: '{{ vars["iam_" + entity_type + "s"] }}'

- name: create IAM {{ entity_type }} {{ entity_name }}
  iam:
    groups: '{{ configured_entities[entity_name]["groups"] | default(omit) }}'
    iam_type: '{{ entity_type }}'
    name: '{{ entity_name }}'
    profile: '{{ profile }}'
    state: present

- include: entity_sync_managed_policies.yml
