---

- name: set IAM entity facts
  set_fact:
    _aws_iam_e: 'IAM {{ _aws_iam_entity_type }} {{ _aws_iam_entity_name }}'

- import_tasks: entity_purge_managed_policies.yml
- import_tasks: entity_purge_inline_policies.yml

- import_tasks: entity_purge_group_users.yml
  when: _aws_iam_entity_type == 'group'

- import_tasks: entity_purge_user_groups.yml
  when: _aws_iam_entity_type == 'user'

- import_tasks: entity_purge_role_instance_profile.yml
  when: _aws_iam_entity_type == 'role'

- name: remove {{ _aws_iam_e }}
  iam:
    profile:        '{{ aws_profile }}'
    aws_access_key: '{{ aws_iam_assume_role_access_key    | default(omit) }}'
    aws_secret_key: '{{ aws_iam_assume_role_secret_key    | default(omit) }}'
    security_token: '{{ aws_iam_assume_role_session_token | default(omit) }}'

    iam_type: '{{ _aws_iam_entity_type }}'
    name: '{{ _aws_iam_entity_name }}'
    state: absent
  register: _aws_iam_remove

- name: call optional notifier
  include_role:
    name: '{{ notifier_role }}'
  vars:
    message: >
      deleted <b>{{ _aws_iam_e }}</b>
      from <a href="{{ _aws_iam_url }}">account {{ aws_profile }}</a>
  when: >
    notifier_role is defined and
    _aws_iam_remove.changed
