---

- name: set member groups fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_member_groups: >
      {{ _aws_iam_aad
         | json_query("UserDetailList[?UserName == `"
                      + _aws_iam_entity_name
                      + "`].GroupList") }}

- name: remove {{ _aws_iam_e }} from groups
  command: >
    aws iam remove-{{ _aws_iam_entity_type }}-from-group
            --group-name '{{ item }}'
            --{{ _aws_iam_entity_type }}-name '{{ _aws_iam_entity_name }}'
            --profile '{{ aws_profile }}'
  with_items: '{{ _aws_iam_member_groups }}'
