---

- name: set IAM entity facts
  set_fact:
    entity_name: '{{ item }}'
    e: 'IAM {{ entity_type }} {{ item }}'
    eurl: https://console.aws.amazon.com/iam/home#{{ entity_type }}s/{{ item }}

- name: set configuration fact for IAM {{ entity_type }}s
  set_fact:
    configured_entities: '{{ vars["iam_" + entity_type + "s"] }}'

- name: create {{ e }}
  iam:
    iam_type: '{{ entity_type }}'
    name: '{{ entity_name }}'
    profile: '{{ aws_profile }}'
    state: present
  register: iam

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      created <a href="{{ eurl }}">{{ e }}</a>
      in <a href="{{ iam_url }}">account {{ aws_profile }}</a>
  when: >
    notifier_role is defined and
    iam.changed
