---

- name: set IAM entity name fact
  set_fact:
    entity_name: '{{ item }}'

- include: entity_detach_managed_policies.yml
- include: entity_delete_inline_policies.yml

- include: entity_remove_group_users.yml
  when: entity_type == 'group'

- include: entity_remove_user_groups.yml
  when: entity_type == 'user'

- include: entity_remove_role_instance_profile.yml
  when: entity_type == 'role'

- name: remove IAM {{ entity_type }} {{ entity_name }}
  iam:
    iam_type: '{{ entity_type }}'
    name: '{{ entity_name }}'
    profile: '{{ profile }}'
    state: absent
  register: iam

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      deleted <b>IAM {{ entity_type }} {{ entity_name }}</b>
      from <b>account {{ profile }}</b>
  when: >
    notifier_role is defined and
    iam.changed
