---

- name: set IAM entity facts
  set_fact:
    _aws_iam_e: 'IAM {{ _aws_iam_entity_type }} {{ _aws_iam_entity_name }}'
    _aws_iam_eurl: >-
      https://console.aws.amazon.com/iam/home#{{
        _aws_iam_entity_type }}s/{{ _aws_iam_entity_name }}

- name: set configuration fact for IAM {{ _aws_iam_entity_type }}s
  set_fact:
    _aws_iam_configured_entities: >
      {{ vars["aws_iam_" + _aws_iam_entity_type + "s"] }}

- import_tasks: entity_sync_managed_policies_facts.yml
- import_tasks: entity_sync_managed_policies_attach.yml
- import_tasks: entity_sync_managed_policies_detach.yml

- import_tasks: entity_sync_inline_policies_facts.yml
- import_tasks: entity_sync_inline_policies_add.yml
- import_tasks: entity_sync_inline_policies_delete.yml
- import_tasks: entity_sync_inline_policies_update.yml

- import_tasks: entity_sync_user_groups.yml
  when: _aws_iam_entity_type == 'user'

- import_tasks: entity_sync_assume_role_policy.yml
  when: _aws_iam_entity_type == 'role'
