---

- name: list instance profiles using {{ e }}
  command: >
    aws iam list-instance-profiles-for-{{ entity_type }}
            --{{ entity_type }}-name '{{ entity_name }}'
            --query 'InstanceProfiles[*].InstanceProfileName'
            --profile '{{ aws_profile }}'
  register: instance_profiles
  changed_when: False

- name: set instance profiles fact for {{ e }}
  set_fact:
    instance_profiles: '{{ instance_profiles.stdout | from_json }}'

- name: remove {{ e }} from instance profiles
  command: >
    aws iam remove-{{ entity_type }}-from-instance-profile
            --instance-profile-name '{{ item }}'
            --{{ entity_type }}-name '{{ entity_name }}'
            --query 'InstanceProfiles[*].InstanceProfileName'
            --profile '{{ aws_profile }}'
  with_items: instance_profiles
