---

- name: set fact for configured IAM {{ _aws_iam_entity_type }}s
  set_fact:
    _aws_iam_configured_entities: >
      {{ vars["aws_iam_" + _aws_iam_entity_type + "s"] | default([]) }}
    _aws_iam_Entity_Type: '{{ _aws_iam_entity_type | capitalize }}'

- name: set fact for existing IAM {{ _aws_iam_entity_type }}s
  set_fact:
    _aws_iam_existing_entities: >
      {{ _aws_iam_aad
         | json_query(_aws_iam_Entity_Type
                      + "DetailList"
                      + "[? ! starts_with(Path, `/aws-service-role/`)]."
                      + _aws_iam_Entity_Type
                      + "Name") }}
