---

- name: set role assumption policy fact for {{ _aws_iam_e }}
  set_fact:
    _aws_iam_assume_role_policy: >-
      {{ _aws_iam_aad
         | json_query("RoleDetailList[?RoleName == `"
                      + _aws_iam_entity_name
                      + "`].AssumeRolePolicyDocument | [0]") }}

- block:

    - name: update role assumption policy for {{ _aws_iam_e }}
      command: >
        aws iam update-assume-role-policy
                --{{ _aws_iam_entity_type }}-name '{{ _aws_iam_entity_name }}'
                --policy-document
                  '{{ _aws_iam_configured_entities
                        [_aws_iam_entity_name]
                        ["assume_role_policy"]
                      | to_nice_json }}'
                --profile '{{ aws_profile }}'

    - name: call optional notifier
      include_role:
        name: '{{ notifier_role }}'
      vars:
        message: >
          updated role assumption policy for
          <a href="{{ _aws_iam_eurl }}">{{ _aws_iam_e }}</a>
          in <a href="{{ _aws_iam_url }}">account {{ aws_profile }}</a>
      when: >
        notifier_role is defined

  when: >
    ( _aws_iam_assume_role_policy == '')
    or
    ( _aws_iam_assume_role_policy
      | sort_json_policy_dict )
    !=
    ( _aws_iam_configured_entities
        [_aws_iam_entity_name]
        ["assume_role_policy"]
      | sort_json_policy_dict )

