---

- name: list managed policies attached to {{ e }}
  command: >
    aws iam list-attached-{{ entity_type }}-policies
            --{{ entity_type }}-name '{{ entity_name }}'
            --query 'AttachedPolicies[*].PolicyArn'
            --profile '{{ profile }}'
  register: attached_managed_policies
  changed_when: False

- name: set attached managed policies fact for {{ e }}
  set_fact:
    attached_managed_policies:
      '{{ attached_managed_policies.stdout | from_json }}'

- name: remove all managed policies for {{ e }}
  command: >
    aws iam detach-{{ entity_type }}-policy
            --{{ entity_type }}-name '{{ entity_name }}'
            --policy-arn '{{ item }}'
            --profile '{{ profile }}'
  with_items: attached_managed_policies
