---

- name: set fact for configured IAM {{ entity_type }}s
  set_fact:
    configured_entities: '{{ vars["iam_" + entity_type + "s"] | default([]) }}'
    Entity_Type: '{{ entity_type | capitalize }}'

- name: list existing IAM {{ entity_type }}s
  command: >
    aws iam list-{{ entity_type }}s
            --query '{{ Entity_Type }}s[*].{{ Entity_Type }}Name'
            --profile '{{ aws_profile }}'
  register: existing_entities
  changed_when: False

- name: set fact for existing IAM {{ entity_type }}s
  set_fact:
    existing_entities: '{{ existing_entities.stdout | from_json }}'
