---

- name: list member groups for IAM {{ entity_type }} {{ entity_name }}
  command: >
    aws iam list-groups-for-{{ entity_type }}
            --{{ entity_type }}-name '{{ entity_name }}'
            --query 'Groups[*].GroupName'
            --profile '{{ profile }}'
  register: member_groups
  changed_when: False

- name: set member groups fact for IAM {{ entity_type }} {{ entity_name }}
  set_fact:
    member_groups: '{{ member_groups.stdout | from_json }}'

- name: remove IAM {{ entity_type }} {{ entity_name }} from groups
  command: >
    aws iam remove-{{ entity_type }}-from-group
            --group-name '{{ item }}'
            --{{ entity_type }}-name '{{ entity_name }}'
            --profile '{{ profile }}'
  with_items: member_groups
