---

- name: set IAM entity facts
  set_fact:
    entity_name: '{{ item }}'
    e: 'IAM {{ entity_type }} {{ item }}'

- include: entity_purge_managed_policies.yml
- include: entity_purge_inline_policies.yml

- include: entity_purge_group_users.yml
  when: entity_type == 'group'

- include: entity_purge_user_groups.yml
  when: entity_type == 'user'

- include: entity_purge_role_instance_profile.yml
  when: entity_type == 'role'

- name: remove {{ e }}
  iam:
    iam_type: '{{ entity_type }}'
    name: '{{ entity_name }}'
    profile: '{{ profile }}'
    state: absent
  register: iam

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      deleted <b>{{ e }}</b>
      from <b>account {{ profile }}</b>
  when: >
    notifier_role is defined and
    iam.changed
