---

- name: list inline policies embedded in {{ e }}
  command: >
    aws iam list-{{ entity_type }}-policies
            --{{ entity_type }}-name '{{ entity_name }}'
            --query 'PolicyNames'
            --profile '{{ profile }}'
  register: embedded_inline_policies
  changed_when: False

- name: set embedded inline policies fact for {{ e }}
  set_fact:
    embedded_inline_policies:
      '{{ embedded_inline_policies.stdout | from_json }}'

- name: delete all inline policies for {{ e }}
  command: >
    aws iam delete-{{ entity_type }}-policy
            --{{ entity_type }}-name '{{ entity_name }}'
            --policy-name '{{ item }}'
            --profile '{{ profile }}'
  with_items: embedded_inline_policies
