---

- name: set global facts
  set_fact:
    _aws_iam_url: 'https://console.aws.amazon.com/iam/home#home'


- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      started running role <b>aws-iam</b>
      on <a href="{{ _aws_iam_url }}">account {{ aws_profile }}</a>
  when: notifier_role is defined


- include: saml_provider_list.yml

- include: saml_provider_create.yml
  with_items: '{{ _aws_iam_configured_saml_providers }}'
  when: _aws_iam_saml_provider_arn not in _aws_iam_existing_saml_providers
  loop_control:
    loop_var: _aws_iam_saml_provider_arn

- include: saml_provider_delete.yml
  with_items: '{{ _aws_iam_existing_saml_providers }}'
  when: _aws_iam_saml_provider_arn not in _aws_iam_configured_saml_providers
  loop_control:
    loop_var: _aws_iam_saml_provider_arn

- include: saml_provider_sync.yml
  with_items: '{{ _aws_iam_configured_saml_providers }}'
  loop_control:
    loop_var: _aws_iam_saml_provider_arn


- include: policy_list.yml

- include: policy_create.yml
  with_items: '{{ _aws_iam_configured_policies }}'
  when: _aws_iam_policy_name not in _aws_iam_existing_policies
  loop_control:
    loop_var: _aws_iam_policy_name

- include: policy_delete.yml
  with_items: '{{ _aws_iam_existing_policies }}'
  when: _aws_iam_policy_name not in _aws_iam_configured_policies
  loop_control:
    loop_var: _aws_iam_policy_name

- include: policy_sync.yml
  with_items: '{{ _aws_iam_configured_policies }}'
  loop_control:
    loop_var: _aws_iam_policy_name


- name: set entity type fact to "group"
  set_fact:
    _aws_iam_entity_type: group

- include: entities_list.yml

- include: entity_create.yml
  with_items: '{{ _aws_iam_configured_entities }}'
  loop_control:
    loop_var: _aws_iam_entity_name

- include: entity_delete.yml
  with_items: '{{ _aws_iam_existing_entities }}'
  when: _aws_iam_entity_name not in _aws_iam_configured_entities
  loop_control:
    loop_var: _aws_iam_entity_name

- include: entity_sync.yml
  with_items: '{{ _aws_iam_configured_entities }}'
  loop_control:
    loop_var: _aws_iam_entity_name


- name: set entity type fact to "user"
  set_fact:
    _aws_iam_entity_type: user

- include: entities_list.yml

- include: entity_create.yml
  with_items: '{{ _aws_iam_configured_entities }}'
  loop_control:
    loop_var: _aws_iam_entity_name

- include: entity_delete.yml
  with_items: '{{ _aws_iam_existing_entities }}'
  when: _aws_iam_entity_name not in _aws_iam_configured_entities
  loop_control:
    loop_var: _aws_iam_entity_name

- include: entity_sync.yml
  with_items: '{{ _aws_iam_configured_entities }}'
  loop_control:
    loop_var: _aws_iam_entity_name


- name: set entity type fact to "role"
  set_fact:
    _aws_iam_entity_type: role

- include: entities_list.yml

- include: entity_create.yml
  with_items: '{{ _aws_iam_configured_entities }}'
  loop_control:
    loop_var: _aws_iam_entity_name

- include: entity_delete.yml
  with_items: '{{ _aws_iam_existing_entities }}'
  when: _aws_iam_entity_name not in _aws_iam_configured_entities
  loop_control:
    loop_var: _aws_iam_entity_name

- include: entity_sync.yml
  with_items: '{{ _aws_iam_configured_entities }}'
  loop_control:
    loop_var: _aws_iam_entity_name


- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      finished running role <b>aws-iam</b>
      on <a href="{{ _aws_iam_url }}">account {{ aws_profile }}</a>
  when: notifier_role is defined
