---

- name: set global facts
  set_fact:
    _aws_iam_url: 'https://console.aws.amazon.com/iam/home#home'


- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      started running role <b>aws-iam</b>
      on <a href="{{ _aws_iam_url }}">account {{ aws_profile }}</a>
  when: notifier_role is defined


- include: saml_provider_list.yml

- include: saml_provider_create.yml saml_provider_name={{ item }}
  with_items: _aws_iam_configured_saml_providers
  when: item not in _aws_iam_existing_saml_providers

- include: saml_provider_delete.yml saml_provider_name={{ item }}
  with_items: _aws_iam_existing_saml_providers
  when: item not in _aws_iam_configured_saml_providers

- include: saml_provider_sync.yml saml_provider_name={{ item }}
  with_items: _aws_iam_configured_saml_providers


- include: policy_list.yml

- include: policy_create.yml policy_name={{ item }}
  with_items: _aws_iam_configured_policies
  when: item not in _aws_iam_existing_policies

- include: policy_delete.yml policy_name={{ item }}
  with_items: _aws_iam_existing_policies
  when: item not in _aws_iam_configured_policies

- include: policy_sync.yml policy_name={{ item }}
  with_items: _aws_iam_configured_policies


- name: set entity type fact to "group"
  set_fact:
    _aws_iam_entity_type: group

- include: entities_list.yml

- include: entity_create.yml entity_name={{ item }}
  with_items: _aws_iam_configured_entities

- include: entity_delete.yml entity_name={{ item }}
  with_items: _aws_iam_existing_entities
  when: item not in _aws_iam_configured_entities

- include: entity_sync.yml entity_name={{ item }}
  with_items: _aws_iam_configured_entities


- name: set entity type fact to "user"
  set_fact:
    _aws_iam_entity_type: user

- include: entities_list.yml

- include: entity_create.yml entity_name={{ item }}
  with_items: _aws_iam_configured_entities

- include: entity_delete.yml entity_name={{ item }}
  with_items: _aws_iam_existing_entities
  when: item not in _aws_iam_configured_entities

- include: entity_sync.yml entity_name={{ item }}
  with_items: _aws_iam_configured_entities


- name: set entity type fact to "role"
  set_fact:
    _aws_iam_entity_type: role

- include: entities_list.yml

- include: entity_create.yml entity_name={{ item }}
  with_items: _aws_iam_configured_entities

- include: entity_delete.yml entity_name={{ item }}
  with_items: _aws_iam_existing_entities
  when: item not in _aws_iam_configured_entities

- include: entity_sync.yml entity_name={{ item }}
  with_items: _aws_iam_configured_entities


- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      finished running role <b>aws-iam</b>
      on <a href="{{ _aws_iam_url }}">account {{ aws_profile }}</a>
  when: notifier_role is defined
