---

- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      started running role <b>aws-iam</b> on <b>account {{ profile }}</b>
  when: notifier_role is defined


- include: entities_list.yml entity_type=group

- include: entity_create.yml entity_type=group entity_name={{ item }}
  with_items: configured_entities

- include: entity_delete.yml entity_type=group entity_name={{ item }}
  with_items: existing_entities
  when: item not in configured_entities


- include: entities_list.yml entity_type=user

- include: entity_create.yml entity_type=user entity_name={{ item }}
  with_items: configured_entities

- include: entity_delete.yml entity_type=user entity_name={{ item }}
  with_items: existing_entities
  when: item not in configured_entities


- include: entities_list.yml entity_type=role

- include: entity_create.yml entity_type=role entity_name={{ item }}
  with_items: configured_entities

- include: entity_delete.yml entity_type=role entity_name={{ item }}
  with_items: existing_entities
  when: item not in configured_entities


- name: call optional notifier
  include: 'roles/{{ notifier_role }}/tasks/main.yml'
  vars:
    message: >
      finished running role <b>aws-iam</b> on <b>account {{ profile }}</b>
  when: notifier_role is defined
