---

- include: entities_list.yml entity_type=group

- include: entity_create.yml entity_type=group entity_name={{ item }}
  with_items: configured_entities

- include: group_delete.yml                    entity_name={{ item }}
  with_items: existing_entities
  when: item not in configured_entities


- include: entities_list.yml entity_type=user

- include: entity_create.yml entity_type=user entity_name={{ item }}
  with_items: configured_entities

- include: user_delete.yml                    entity_name={{ item }}
  with_items: existing_entities
  when: item not in configured_entities


- include: entities_list.yml entity_type=role

- include: entity_create.yml entity_type=role entity_name={{ item }}
  with_items: configured_entities

- include: role_delete.yml                    entity_name={{ item }}
  with_items: existing_entities
  when: item not in configured_entities
