---

- name: set configured IAM managed policies fact
  set_fact:
    _aws_iam_configured_policies: >
      {{ vars["aws_iam_policies"] | default([]) }}

- name: initialize existing IAM managed policies fact
  set_fact:
    _aws_iam_existing_policies: {}

- name: set existing IAM managed policies fact
  set_fact:
    _aws_iam_existing_policies: >
      {{ _aws_iam_existing_policies
         | combine({item.PolicyName: item}) }}
  with_items: >
    {{ _aws_iam_aad.Policies
       | rejectattr("Arn", "match", "^arn:aws:iam::aws:policy/")
       | list }}
