---

- name: set IAM managed policy path fact
  set_fact:
    _aws_iam_policy_path: >-
      {{ _aws_iam_configured_policies[_aws_iam_policy_name]["path"]
         | default("/") }}

- name: set IAM managed policy ARN fact
  set_fact:
    _aws_iam_policy_arn: >-
      arn:aws:iam::{{ aws_account }}:policy{{
        _aws_iam_policy_path }}{{ _aws_iam_policy_name }}

- name: set IAM managed policy facts
  set_fact:
    _aws_iam_p: 'IAM managed policy {{ _aws_iam_policy_name }}'
    _aws_iam_purl: >-
      https://console.aws.amazon.com/iam/home#policies/{{ _aws_iam_policy_arn }}

- name: create {{ _aws_iam_p }}
  command: >
    aws iam create-policy
            --path '{{ _aws_iam_policy_path }}'
            --policy-name '{{ _aws_iam_policy_name }}'
            --policy-document
              '{{ _aws_iam_configured_policies[_aws_iam_policy_name]["document"]
                  | to_nice_json }}'
            --profile '{{ aws_profile }}'

- name: call optional notifier
  include_role:
    name: '{{ notifier_role }}'
  vars:
    message: >
      created <a href="{{ _aws_iam_purl }}">{{ _aws_iam_p }}</a>
      in <a href="{{ _aws_iam_url }}">account {{ aws_profile }}</a>
  when: >
    notifier_role is defined
