---

- name: list instance profiles using IAM {{ entity_type }} {{ entity_name }}
  command: |
    aws iam list-instance-profiles-for-{{ entity_type }}
            --{{ entity_type }}-name '{{ entity_name }}'
            --query 'InstanceProfiles[*].InstanceProfileName'
            --profile '{{ profile }}'
  register: instance_profiles
  changed_when: False

- name: set instance profiles fact for IAM {{ entity_type }} {{ entity_name }}
  set_fact:
    instance_profiles: '{{ instance_profiles.stdout | from_json }}'

- name: remove IAM {{ entity_type }} {{ entity_name }} from instance profiles
  command: |
    aws iam remove-{{ entity_type }}-from-instance-profile
            --instance-profile-name '{{ item }}'
            --{{ entity_type }}-name '{{ entity_name }}'
            --query 'InstanceProfiles[*].InstanceProfileName'
            --profile '{{ profile }}'
  with_items: instance_profiles

- name: list policies attached to IAM {{ entity_type }} {{ entity_name }}
  command: |
    aws iam list-attached-{{ entity_type }}-policies
            --{{ entity_type }}-name '{{ entity_name }}'
            --query 'AttachedPolicies[*].PolicyArn'
            --profile '{{ profile }}'
  register: attached_policies
  changed_when: False

- name: set attached policies fact for IAM {{ entity_type }} {{ entity_name }}
  set_fact:
    attached_policies: '{{ attached_policies.stdout | from_json }}'

- name: remove all policies for IAM {{ entity_type }} {{ entity_name }}
  command: |
    aws iam detach-{{ entity_type }}-policy
            --{{ entity_type }}-name '{{ entity_name }}'
            --policy-arn '{{ item }}'
            --profile '{{ profile }}'
  with_items: attached_policies

- name: remove IAM {{ entity_type }} {{ entity_name }}
  command: |
    aws iam delete-{{ entity_type }}
            --{{ entity_type }}-name '{{ entity_name }}'
            --profile '{{ profile }}'
