---

- name: set configured IAM SAML provider fact
  set_fact:
    _aws_iam_configured_saml_providers: >
      {{ vars["aws_iam_saml_providers"] | default([]) }}

- name: list existing IAM SAML providers
  command: >
    aws iam list-saml-providers
            --query 'SAMLProviderList[*].Arn'
            --profile '{{ aws_profile }}'
  register: _aws_iam_existing_saml_providers
  changed_when: False

- name: set existing IAM SAML providers fact
  set_fact:
    _aws_iam_existing_saml_providers: >
      {{ _aws_iam_existing_saml_providers.stdout | from_json }}
